"""
Intelligence pipeline with:
  - Stage 1: cheap title-only relevance filter (idea 2)
  - Stage 2: batched full analysis, up to BATCH_SIZE articles per API call (idea 1)
  - Cost tracking on every call
"""
import json
import anthropic
from pathlib import Path

client = anthropic.Anthropic()
SYSTEM_PROMPT = Path("prompts/intel_filter.txt").read_text()

_KB_PATH = Path("prompts/zoom_knowledge.md")
_KB = _KB_PATH.read_text(encoding="utf-8").strip() if _KB_PATH.exists() else ""
if _KB:
    SYSTEM_PROMPT = f"{_KB}\n\n---\n\n" + SYSTEM_PROMPT

BATCH_SIZE = 5    # articles per API call
MAX_TOKENS_PER_ITEM = 700   # sub_scores + heat back in Claude output

# claude-haiku-4-5 pricing (USD per token)
_IN   = 0.80  / 1_000_000   # regular input
_OUT  = 4.00  / 1_000_000   # output
_CW   = 1.00  / 1_000_000   # cache write
_CR   = 0.08  / 1_000_000   # cache read

# Accumulated per-call stats for the current run; flushed to DB by main.py
_call_log: list[dict] = []

try:
    _tok = client.messages.count_tokens(
        model="claude-haiku-4-5",
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": "x"}],
    )
    print(f"[INFO] System prompt: {_tok.input_tokens:,} tokens "
          f"(~${_tok.input_tokens * _CW:.4f} cache-write / "
          f"${_tok.input_tokens * _CR:.4f} cache-read per call)")
except Exception:
    pass

QUICK_SYSTEM = (
    "CCaaS competitive intelligence relevance filter. "
    "Given an article title, respond ONLY with JSON: "
    '{\"relevant\":true} or {\"relevant\":false}. No other text.'
)


def _calc_cost(usage) -> float:
    return (
        getattr(usage, "input_tokens", 0)               * _IN  +
        getattr(usage, "output_tokens", 0)              * _OUT +
        getattr(usage, "cache_creation_input_tokens", 0) * _CW  +
        getattr(usage, "cache_read_input_tokens", 0)    * _CR
    )


def _extract_json_object(raw: str) -> str:
    """Pull the first complete {...} block from raw text, ignoring preamble/postamble."""
    if raw.startswith("```"):
        lines = raw.splitlines()
        inner = lines[1:]
        if inner and inner[-1].strip() == "```":
            inner = inner[:-1]
        raw = "\n".join(inner).strip()
    brace = raw.find("{")
    if brace > 0:
        raw = raw[brace:]
    depth = end = 0
    for i, ch in enumerate(raw):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    return raw[:end] if end else raw


def _extract_json_array(raw: str) -> str:
    """Pull the first complete [...] array from raw text."""
    if raw.startswith("```"):
        lines = raw.splitlines()
        inner = lines[1:]
        if inner and inner[-1].strip() == "```":
            inner = inner[:-1]
        raw = "\n".join(inner).strip()
    bracket = raw.find("[")
    if bracket > 0:
        raw = raw[bracket:]
    depth = end = 0
    for i, ch in enumerate(raw):
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    return raw[:end] if end else raw


def _derive_fields(insight: dict, item: dict) -> dict:
    """
    Inject fields that are already known from the item and don't require article reading.
    sub_scores and heat are generated by Claude; only metadata is filled here.
    """
    tier = item.get("tier", 1)
    insight["competitor"]  = item.get("competitor", "")
    insight["source_url"]  = item.get("url", "")
    insight["source_type"] = "primary" if tier == 1 else "secondary"
    insight["heat_delta"]  = 0
    return insight


def quick_filter(item: dict) -> tuple[bool, float]:
    """
    Stage-1: title-only relevance check.
    Returns (is_relevant, cost_usd).
    Fails open (returns True) on any error.
    """
    try:
        resp = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=20,
            system=QUICK_SYSTEM,
            messages=[{"role": "user", "content": f"Title: {item['title']}"}],
        )
        cost = _calc_cost(resp.usage)
        _call_log.append({
            "stage": "quick_filter",
            "batch_size": 1,
            "input_tokens": getattr(resp.usage, "input_tokens", 0),
            "output_tokens": getattr(resp.usage, "output_tokens", 0),
            "cache_read_tokens": getattr(resp.usage, "cache_read_input_tokens", 0),
            "cache_creation_tokens": getattr(resp.usage, "cache_creation_input_tokens", 0),
            "cost_usd": cost,
        })
        raw = resp.content[0].text.strip()
        result = json.loads(_extract_json_object(raw))
        return bool(result.get("relevant", True)), cost
    except Exception as e:
        print(f"[WARN] quick_filter failed for '{item['title'][:60]}': {e}")
        return True, 0.0


def analyze_batch(items: list[dict]) -> list[tuple[dict | None, float]]:
    """
    Stage-2: analyze up to BATCH_SIZE items in a single API call.
    Returns list of (insight_dict | None, cost_per_item).
    Falls back to empty results (not individual calls) on total failure.
    """
    n = len(items)
    if n == 0:
        return []

    parts = []
    for i, item in enumerate(items, 1):
        parts.append(
            f"ARTICLE {i}:\n"
            f"Competitor: {item['competitor']}\n"
            f"Title: {item['title']}\n"
            f"URL: {item['url']}\n"
            f"Content: {(item.get('summary') or item.get('content') or '')[:2000]}\n"
            f"Published: {item.get('published', '')}"
        )

    if n == 1:
        user_content = parts[0].replace("ARTICLE 1:\n", "")
    else:
        user_content = (
            f"Analyze the following {n} articles. "
            f"Return a JSON array with exactly {n} objects in the same order. "
            f"Each object must follow your output schema exactly.\n\n"
            + "\n\n".join(parts)
        )

    try:
        resp = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=min(4096, MAX_TOKENS_PER_ITEM * n),
            system=[{"type": "text", "text": SYSTEM_PROMPT, "cache_control": {"type": "ephemeral"}}],
            messages=[{"role": "user", "content": user_content}],
            extra_headers={"anthropic-beta": "prompt-caching-2024-07-31"},
        )
        cost = _calc_cost(resp.usage)
        cost_per_item = cost / n
        _call_log.append({
            "stage": "analyze_batch",
            "batch_size": n,
            "input_tokens": getattr(resp.usage, "input_tokens", 0),
            "output_tokens": getattr(resp.usage, "output_tokens", 0),
            "cache_read_tokens": getattr(resp.usage, "cache_read_input_tokens", 0),
            "cache_creation_tokens": getattr(resp.usage, "cache_creation_input_tokens", 0),
            "cost_usd": cost,
        })
        raw = resp.content[0].text.strip()

        if n == 1:
            insight = _derive_fields(json.loads(_extract_json_object(raw)), items[0])
            return [(insight, cost_per_item)]

        arr = json.loads(_extract_json_array(raw))
        if not isinstance(arr, list):
            arr = [arr]
        while len(arr) < n:
            arr.append(None)
        results = []
        for item, ins in zip(items, arr[:n]):
            if isinstance(ins, dict):
                ins = _derive_fields(ins, item)
            results.append((ins if isinstance(ins, dict) else None, cost_per_item))
        return results

    except Exception as e:
        print(f"[WARN] analyze_batch({n} items) failed: {e}")
        return [(None, 0.0)] * n


def analyze_item(item: dict) -> tuple[dict | None, float]:
    """Convenience wrapper for a single item. Returns (insight, cost_usd)."""
    results = analyze_batch([item])
    return results[0]
